[2024-11-08T18:04:39.818+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-08T18:04:39.901+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_monitoring.system_health_check manual__2024-11-08T18:04:24.028045+00:00 [queued]>
[2024-11-08T18:04:39.967+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_monitoring.system_health_check manual__2024-11-08T18:04:24.028045+00:00 [queued]>
[2024-11-08T18:04:39.967+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-08T18:04:40.032+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): system_health_check> on 2024-11-08 18:04:24.028045+00:00
[2024-11-08T18:04:40.070+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=569) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-08T18:04:40.073+0000] {standard_task_runner.py:72} INFO - Started process 571 to run task
[2024-11-08T18:04:40.079+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_monitoring', 'system_health_check', 'manual__2024-11-08T18:04:24.028045+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/monitoring_dag.py', '--cfg-path', '/tmp/tmpxk5ba__z']
[2024-11-08T18:04:40.146+0000] {standard_task_runner.py:105} INFO - Job 166: Subtask system_health_check
[2024-11-08T18:04:40.283+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_monitoring.system_health_check manual__2024-11-08T18:04:24.028045+00:00 [running]> on host 641085defe8e
[2024-11-08T18:04:40.709+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fraud_team' AIRFLOW_CTX_DAG_ID='fraud_monitoring' AIRFLOW_CTX_TASK_ID='system_health_check' AIRFLOW_CTX_EXECUTION_DATE='2024-11-08T18:04:24.028045+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-08T18:04:24.028045+00:00'
[2024-11-08T18:04:40.715+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-08T18:04:53.267+0000] {monitoring_dag.py:23} ERROR - Erreur API: HTTPSConnectionPool(host='real-time-payments-api.herokuapp.com', port=443): Read timed out. (read timeout=10)
[2024-11-08T18:05:08.994+0000] {monitoring_dag.py:48} INFO - Accès S3 vérifié: bucket=fraud-detection-bucket-jedha, prefix=
[2024-11-08T18:05:12.794+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-08T18:05:12.930+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-08T18:05:12.939+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fraud_monitoring, task_id=system_health_check, run_id=manual__2024-11-08T18:04:24.028045+00:00, execution_date=20241108T180424, start_date=20241108T180439, end_date=20241108T180512
[2024-11-08T18:05:13.102+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-08T18:05:13.152+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-08T18:05:13.156+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
