[2024-11-23T17:20:56.928+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T17:20:56.955+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection.log_to_mlflow scheduled__2024-11-23T17:19:00+00:00 [queued]>
[2024-11-23T17:20:56.969+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection.log_to_mlflow scheduled__2024-11-23T17:19:00+00:00 [queued]>
[2024-11-23T17:20:56.970+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-23T17:20:56.995+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): log_to_mlflow> on 2024-11-23 17:19:00+00:00
[2024-11-23T17:20:57.019+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2135) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-23T17:20:57.021+0000] {standard_task_runner.py:72} INFO - Started process 2140 to run task
[2024-11-23T17:20:57.023+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection', 'log_to_mlflow', 'scheduled__2024-11-23T17:19:00+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_dag.py', '--cfg-path', '/tmp/tmpqvf5un_o']
[2024-11-23T17:20:57.034+0000] {standard_task_runner.py:105} INFO - Job 213: Subtask log_to_mlflow
[2024-11-23T17:20:57.296+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_detection.log_to_mlflow scheduled__2024-11-23T17:19:00+00:00 [running]> on host 345e92ff26bf
[2024-11-23T17:20:57.579+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fraud_team' AIRFLOW_CTX_DAG_ID='fraud_detection' AIRFLOW_CTX_TASK_ID='log_to_mlflow' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T17:19:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-23T17:19:00+00:00'
[2024-11-23T17:20:57.581+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T17:21:03.655+0000] {fraud_detection_dag.py:409} INFO - Expérience existante utilisée : fraud_detection_pipeline (ID: 1)
[2024-11-23T17:21:03.789+0000] {logging_mixin.py:190} WARNING - 2024/11/23 17:21:03 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-11-23T17:21:20.697+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-11-23T17:22:07.270+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-23T17:22:07.313+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T17:22:07.315+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fraud_detection, task_id=log_to_mlflow, run_id=scheduled__2024-11-23T17:19:00+00:00, execution_date=20241123T171900, start_date=20241123T172056, end_date=20241123T172207
[2024-11-23T17:22:07.404+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-23T17:22:07.469+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T17:22:07.482+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
